apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: projectApp
data:
  default.conf:
    server {
        listen 80;
        location / {
            return 200 "OK";
        }
    }