pipeline {
  agent any
  environment {
    PASSWORD=credentials('docker_password')
  }
  stages {
    stage('Build Docker images') {
      steps {
        sh 'chmod +x ./jenkins_stuff/jenkins_scripts/docker-image-build.sh'
        sh './jenkins_stuff/jenkins_scripts/docker-image-build.sh'
      }
    }
    stage('Pull images down from DockerHub to test vm') {
      steps {
        sh 'chmod +x ./jenkins_stuff/jenkins_scripts/put-images-on-testvm.sh'
        sh './jenkins_stuff/jenkins_scripts/put-images-on-testvm.sh' 
      }
    }
    stage('Build containers to store images, run them.') {
      steps {
        sh 'chmod +x ./jenkins_stuff/jenkins_scripts/build-containers.sh'
        sh './jenkins_stuff/jenkins_scripts/build-containers.sh'
      }
    }
  }
}
