pipeline {
  agent any
  stages {
    stage('Build Docker images') {
      steps {
        chmod +x './jenkins_stuff/jenkins_scripts/docker-image-build.sh'
        sh './jenkins_stuff/jenkins_scripts/docker-image-build.sh'
      }
    }
    stage('Pull images down from DockerHub to test vm') {
      steps {
        sh './jenkins_stuff/jenkins_scripts/put-images-on-testvm.sh' 
      }
    }
    stage('Build containers to store images') {
      steps {
        sh './jenkins_stuff/jenkins_scripts/build-containers.sh'
      }
    }
  }
}
