apiVersion: v1
kind: Pod
metadata:
  name: backendApp
  namespace: projectApp
  labels:
    app: backendApp
spec:
  containers:
  - name: backendApp
    image: lukef2021/backend
    ports:
    - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: backendApp
  namespace: projectApp
  labels:
    app: backendApp
spec:
  selector:
    app: backendApp
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP