apiVersion: v1
kind: Pod
metadata:
  name: frontendApp
  namespace: projectApp
  labels:
    app: frontendApp
spec:
  containers:
  - name: frontendApp
    image: lukef2021/frontend
    ports:
    - containerPort: 5000